VERSION = "v0.1.000"
WINDOW_HEIGHT = 16
WINDOW_SIZE = (800 + WINDOW_HEIGHT, 600 + WINDOW_HEIGHT)
FONT_SIZE = 14 if WINDOW_HEIGHT > 14 else WINDOW_HEIGHT

FOOD_SIZE = 4
ENTITY_SIZE = 5
EGG_SIZE = 3
ENTITY_WINDOW_BORDER = ENTITY_SIZE * 2
HUNTER_COLOR = "orangered"
PREY_COLOR = "cyan"
FOOD_COLOR = (0, 150, 100)
MATE_COLOR = "pink"
EGG_COLOR = "blue"
