import icecream

icecream.ic.includeContext = True

VERSION = "v0.1.000"
PIXEL_BORDER = 16
WINDOW_SIZE = (800 + PIXEL_BORDER, 600 + PIXEL_BORDER)
FONT_SIZE = 14 if PIXEL_BORDER > 14 else PIXEL_BORDER

ENTITY_SIZE = 5
ENTITY_WINDOW_BORDER = ENTITY_SIZE * 2

HUNTER_COLOR = "orangered"
PREY_COLOR = "cyan"
MATE_COLOR = "pink"

FOOD_COLOR = (0, 150, 100)
FOOD_SIZE = 4
MUTATED_FOOD_COLOR = "yellow"
MUTATED_FOOD_CHANCE = 1

EGG_COLOR = "blue"
EGG_SIZE = 3
